### ISSUE TITLE
Generated controller names should be pluralized

### ISSUE THREAD

**Issue by james-t-g** [dhumphreys/cfwheels-coldroute#1]
Hey Don,

In the coldroute/coldroute.cfc component, can the default controller to use be the pluralized name of the controller? Line 292 would change to look something like this:

``` coldfusion
<cfargument name="member" type="string" default="#!arguments.$plural ? pluralize(arguments.name) : arguments.name#" />
```

Let me know what you think.

James

**Comment by james-t-g** [comment]
Well, after a bit more digging, i think the resources method can be left alone. Maybe a check right before addRoute() is called in match() to pluralize the controller name if the setting is present?

**Comment by dhumphreys** [comment]
I was thinking about this the other day. Rails defaults to plural controllers for resource routes. Our policy at work is to have them singular. I should probably make them default to plural and enable some sort of option to switch them to singular.

**Comment by james-t-g** [comment]
Awesome, I am glad you agree.

**Comment by dhumphreys** [comment]
@liferealized  all controller names for `resource()` and `resources()` will be pluralized now. You can call `set(resourceControllerNaming="singular")` in your wheels settings.cfm file to force them to be singular. Or `set(resourceControllerNaming="name")` to force them to match the resource name (i.e. singular for `resource()` and plural for `resources()`).

Also, calling `resources("fish")` or any other "uncountable" name will result in the plural named routes being suffixed with "index". This means the helpers would be: `fishIndexPath()`, `fishPath(key)`, `newFishPath()`, and `editFishPath(key)`.

**Comment by james-t-g** [comment]
Nice!
