### ISSUE TITLE
Some routes are generated with trailing "/"

### ISSUE THREAD

**Issue by james-t-g** [dhumphreys/cfwheels-coldroute#2]
I haven't dug in to see where this is happening, but some routes are generated in linkTo() with an ending "/". While this does not hurt the application, I think consistency is important. IMO i think all routes should not have the trailing slashes.

**Comment by dhumphreys** [comment]
Agreed. I initially was putting leading and trailing slashes on everything thinking that they were required. I think that both leading and trailing should be omitted as long as everything still works. This is cleanup that remains from the beginning of the project.
