### ISSUE TITLE
Get coldroute working with wheels apps in sub-directories

### ISSUE THREAD

**Issue by dhumphreys** [dhumphreys/cfwheels-coldroute#7]
The plugin currently will not load the correct files when the wheels app is not the website root. Will need to call `$createObjectFromRoot` wheels function instead of manually initializing coldroute component.

**Comment by dhumphreys** [comment]
See Tony's post in http://groups.google.com/group/cfwheels/browse_thread/thread/a5e695e62b1d3143 for more information.

**Comment by dhumphreys** [comment]
@rip747, @mcraig could you see if this works with apps in sub directories? I have just posted an alpha release in the Downloads section that has this fix in it.

**Comment by ghost** [comment]
Will do.

**Comment by rip747** [comment]
i'll see if i can get a chance to play with this over the weekend
